### ISSUE TITLE
Was the option to have barriers to entry (increasing phi) removed?

### ISSUE THREAD

**Issue by jabbring** [jtilly/very-simple-markov-perfect#1]
I noticed that the final commit (408293f) of `valueFunctionIteration.m` removes the possibility that Param.phi is a vector. That seems to go a bit beyond the comment "Update documentation". What happened here?

**Comment by jtilly** [comment]
I guess I was using the broad definition of "documentation."

Yes, in the commit, `phi` becomes a scalar. Not sure exactly why I did it. I probably thought that there was no point in having this minor complication in the code given that it is neither used in the econometric implementation nor properly explained in the exposition, where we refer to the entry costs just as `\varphi`.

Putting the feature back in is straightforward. It requires tiny edits [here](https://github.com/jtilly/very-simple-empirics-sandbox/blob/master/randomFirms.m#L64), [here](https://github.com/jtilly/very-simple-empirics-sandbox/blob/master/valueFunctionIteration.m#L129), [here](https://github.com/jtilly/very-simple-empirics-sandbox/blob/master/example.m#L96), and [here](https://github.com/jtilly/very-simple-empirics-sandbox/blob/master/example.m#L170).

**Comment by jabbring** [comment]
Thanks for the pointers. I do not need it now (econometrics master course), but my empirical IO course had a bit about barriers to entry, so I may return to this in half a year.
